# 梯度下降算法

In [1]:
import os
import warnings

os.environ["TF_CPP_MIN_LOG_LEVEL"] = '3'
warnings.filterwarnings("ignore")

import tensorflow as tf

opt =  tf.keras.optimizers.SGD(learning_rate=0.1)

var = tf.Variable(1.0)

loss = lambda:(var**2)/2.0

opt.minimize(loss, [var]).numpy()

var.numpy()

0.9

# 梯度下降的划分

### 术语
* Epoch: 使用训练集的全部数据进行一次完整训练，称为**一代训练**
* Batch: 使用训练集中的一小部分样本对模型权重进行一次反向传播的参数更新，这一小部分样本称为**一批数据**
* Iteration: 使用一个Batch数据对模型进行一次参数更新的过程，称为**一次训练**

### 梯度下降的划分
* BGD: 每次迭代需要计算每个样本上损失函数的梯度并求和
* SGD: 每次迭代只采样一个样本，计算损失函数在这个样本上的梯度并更新参数
* Mini-Batch: 每次迭代时随机选取一小部分训练样本来计算梯度并更新参数

# 反向传播

## 前向传播
## 反向传播

# 梯度下降的优化

## 动量法（Momentum）
动量梯度下降计算梯度的指数加权平均数，并利用该值来更新参数

In [2]:
opt= tf.keras.optimizers.SGD(lr=0.1, momentum=0.9)

var = tf.Variable(1.0)
val0 = var.value()

loss = lambda:(var**2)/2.0

opt.minimize(loss,[var]).numpy()
val1 = var.value()

opt.minimize(loss,[var]).numpy()
val2 = var.value()

In [3]:
val0

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [4]:
val1

<tf.Tensor: shape=(), dtype=float32, numpy=0.9>

In [5]:
val2

<tf.Tensor: shape=(), dtype=float32, numpy=0.71999997>

## AdaGrad

In [6]:
opt = tf.keras.optimizers.Adagrad(learning_rate=0.1, initial_accumulator_value=0.1, epsilon=1e-7)

var = tf.Variable(1.0)
val0 = var.value()

loss = lambda:(var**2)/2.0

opt.minimize(loss,[var]).numpy()
val1 = var.value()

val1

<tf.Tensor: shape=(), dtype=float32, numpy=0.9046537>

## RMSprop

In [7]:
opt = tf.keras.optimizers.RMSprop(lr=0.1, rho=0.9)

var = tf.Variable(1.0)

loss = lambda:(var**2)/2.0

opt.minimize(loss,[var]).numpy()
val1 = var.value()

val1

<tf.Tensor: shape=(), dtype=float32, numpy=0.6837723>

## Adam

In [8]:
opt = tf.keras.optimizers.Adam(lr=0.1)
var = tf.Variable(1.0)

loss = lambda:(var**2)/2.0

opt.minimize(loss,[var]).numpy()
val1 = var.value()

val1

<tf.Tensor: shape=(), dtype=float32, numpy=0.89999735>

# 学习率退火
在训练神经网络时，一般情况下学习率都会随着训练而变化

原因是：在网络训练的后期，如果学习率过高，会造成loss震荡，但是如果过小，就会造成收敛缓慢的情况

分段常数衰减

指数衰减

1/t衰减

# 正则化

只有训练的时候加正则化，测试时不需要加正则化！
L1、L2正则化，提前终止，Dropout

## Dropout
在训练时会随机丢弃一部分神经元，模型在测试阶段会使用所有神经元

In [11]:
import numpy as np
import tensorflow as tf

layer = tf.keras.layers.Dropout(0.2, input_shape=(2,))

data = np.arange(1, 11).reshape(5, 2).astype(np.float32)

print(data)

outputs = layer(data, training = True)

print(outputs)

[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]
 [ 9. 10.]]
tf.Tensor(
[[ 1.25  0.  ]
 [ 3.75  5.  ]
 [ 6.25  7.5 ]
 [ 8.75  0.  ]
 [11.25 12.5 ]], shape=(5, 2), dtype=float32)


# 批标准化（Batch Normalization）
